### ISSUE TITLE
Examples from readme involving the `let` helper do not seem to work

### ISSUE THREAD

**Issue by Duder-onomy** [lifeart/ember-ref-modifier#157]
I have a simple twiddle demonstrating what I am finding in my app:
https://ember-twiddle.com/106feb8ed164fd0151963b4bbc43aba4?openFiles=templates.application.hbs%2C

I would have expected the `ref` modifier to have set the element by the time the template proceeding it was rendered. I can confirm that `installModifier` is called, but it is definitely called too late. 

This example from the readme DOES work:
```
<div {{ref this "divContainer" }}></div>
{{#-in-element this.divContainer}}
  Hello!
{{/-in-element}}
```

This example does NOT work (the ctx.inputNode.id is undefined)
```
{{#let (hash) as |ctx|}}
	<input id="name-input" {{ref ctx 'inputNode'}}>
	<label for={{ctx.inputNode.id}}> Enter your name </label>
{{/let}}
```

I suspect it has something to do with the `let` helper? 

Is this the expected behavior?  Happy to provide more information. ( thanks for the awesome modifier )

**Comment by Duder-onomy** [comment]
I was able to write a failing test for use with the `let` helper in my fork: https://github.com/Duder-onomy/ember-ref-modifier/blob/failing-test-for-the-let-helper/tests/integration/modifiers/ref-test.js#L109

**Comment by lifeart** [comment]
Hi! Examples mention “hash” must return an ember object, default ember hash helper return plain object.

You need to create custom “hash-object” helper and return new ember  object inside it

**Comment by Duder-onomy** [comment]
Oh snap

**Comment by Duder-onomy** [comment]
Ok, you are totally right. 

If anyone gets here via googling, here is an updated twiddle using a custom hash helper and not the default one: https://ember-twiddle.com/6a36223cd0685e590e45ed5ff3628707?openFiles=templates.application.hbs%2C
