### ISSUE TITLE
Path to 1.0?

### ISSUE THREAD

**Issue by jrjohnson** [lifeart/ember-ref-modifier#197]
Given that this is the [officially recommended solution](https://guides.emberjs.com/release/components/template-lifecycle-dom-and-modifiers/#toc_communicating-between-elements-in-a-component) for this problem I'd be interested in helping get it to `1.0`.

Until that first major version is released Ember Dependency Lint fails tests as many different 0.1.x and 0.2.x versions collide.

**Comment by lifeart** [comment]
Hi @jrjohnson! Thank you for question!
I think we ready for 1.0, there is some tasks to do:

- [x] remove deprecated code https://github.com/lifeart/ember-ref-modifier/blob/master/addon/modifiers/ref.js#L21
- [x] update CI to support 3.12 https://travis-ci.com/lifeart/ember-ref-modifier/jobs/281873563
- [x] update readme to point proper ember versions.

**Comment by jrjohnson** [comment]
Ok, I took a stab at these since I had some free time tonight. Hopefully that's helpful and not annoying 😜

**Comment by lifeart** [comment]
@jrjohnson sure, thank you for your help!

**Comment by lifeart** [comment]
https://github.com/lifeart/ember-ref-modifier/pull/201

**Comment by lifeart** [comment]
@jrjohnson thank you for your time! ember-ref-modifier@1.0.0 released

**Comment by jrjohnson** [comment]
Happy to help!
