### ISSUE TITLE
Argument order

### ISSUE THREAD

**Issue by wycats** [lifeart/ember-ref-modifier#3]
I've been working with this library and I think it's a really important library for users of Glimmer components.

I was using it for writing a cookbook example, and it seemed to me that it would make sense to swap the argument order from:

```hbs
<div {{ref "name" this}}>
```

to:

```hbs
<div {{ref this "name"}}>
```

This matches more closely to `this["name"] = ...` and also matches the Ember run-loop API, which has a similar concern.

In general, I find it clearer when the object you're assigning to is first 😄

**Comment by lifeart** [comment]
@wycats nice catch! I think I can create version with different ordering and add deprecation for existing.

**Comment by lifeart** [comment]
Implemented in `ember-ref-modifier@0.1.2`
